import { defineCollection, z } from 'astro:content';

/**
 * The register. Generated by `node tools/gen-projects.mjs` from previews/assets/register.js,
 * which is count-verified against the 2026 company profile: 73 projects, 9 sectors,
 * 59 with a stated connected load. Private residences carry locality + load only.
 */
const projects = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    sector: z.enum(['it', 'gov', 'hos', 'cpx', 'ind', 'res', 'apt', 'shw', 'key']),
    sectorName: z.string(),
    sectorBlurb: z.string(),
    locality: z.string(),
    /** As printed on the register, e.g. "1000 KVA". Empty when recorded by area. */
    load: z.string(),
    /** Normalised to kVA for sorting and comparison. Null when recorded by area. */
    loadKva: z.number().nullable(),
    /** Discs in the insulator string that supply class implies: 0 when recorded by area. */
    discs: z.number().int().min(0).max(10),
    /** Architect and electrical consultant of record, plus the scope note, as recorded. */
    recordedAs: z.string(),
    classNote: z.string(),
    key: z.boolean().default(false),
    order: z.number().int(),
  }),
});

export const collections = { projects };
